FROM armv7/armhf-archlinux:2015-02
MAINTAINER Jonathan Tron <jonathan@tron.name>

ADD qemu-arm-static /usr/bin/
ADD qemu-arm-static-wrap /usr/bin/

ENV HOME /root
ADD . /build

RUN /build/prepare.sh && \
    /build/install_erlang.sh && \
    /build/install_elixir.sh && \
    /build/cleanup.sh

# Elixir don't behave correctly when locale is not UTF-8
ENV LANG en_US.UTF-8
